limit_req_zone $binary_remote_addr zone=general:10m rate=3r/m;

server {
    listen 80;
    server_name andtech-async.my.id www.andtech-async.my.id;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.andtech-async.my.id andtech-async.my.id;

    ssl_certificate /etc/letsencrypt/live/andtech-async.my.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/andtech-async.my.id/privkey.pem;

    root /var/www/public;
    index index.php;
    client_max_body_size 50M;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
    }
    location / {
        # rate limit configs
        limit_req zone=general burst=2 nodelay;
        limit_req_status 429;
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
    location ~ /\.ht { deny all; }
    location ~* \.(js|css|png|jpg|gif|ico|svg|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}